// SME and micro-business service categories for Found Local + Already Done pipeline.
// Focused on: people who get in a van, small service providers, micro retail units.
// All categories are used as Google Places text search queries ("category in location").

export const categories = [

  // ── Plumbing, heating, gas ──────────────────────────────────────────────
  'plumber',
  'gas engineer',
  'heating engineer',
  'boiler repair',
  'boiler installation',
  'underfloor heating installer',
  'oil boiler engineer',
  'heat pump installer',
  'air source heat pump installer',
  'water softener installer',
  'shower installer',
  'wet room fitter',

  // ── Electrical ──────────────────────────────────────────────────────────
  'electrician',
  'electrical contractor',
  'solar panel installer',
  'ev charger installer',
  'tv aerial installer',
  'satellite dish installer',
  'alarm installer',
  'cctv installer',
  'smart home installer',
  'PAT testing',
  'auto electrician',
  'fire alarm installer',

  // ── Building & structural ────────────────────────────────────────────────
  'builder',
  'bricklayer',
  'groundworker',
  'loft conversion specialist',
  'extension builder',
  'conservatory installer',
  'garage conversion specialist',
  'basement conversion specialist',
  'stonemason',
  'structural engineer',
  'listed building specialist',

  // ── Roofing & exterior ───────────────────────────────────────────────────
  'roofer',
  'flat roofer',
  'chimney sweep',
  'fascia and soffit fitter',
  'guttering specialist',
  'gutter cleaner',
  'rendering specialist',
  'external wall insulation installer',
  'cavity wall insulation installer',
  'lead work specialist',
  'thatcher',

  // ── Windows, doors, glazing ──────────────────────────────────────────────
  'glazier',
  'double glazing installer',
  'window cleaner',
  'locksmith',
  'composite door installer',
  'garage door installer',
  'sash window restorer',

  // ── Interior trades ──────────────────────────────────────────────────────
  'painter and decorator',
  'plasterer',
  'coving specialist',
  'tiler',
  'flooring installer',
  'floor sanding specialist',
  'carpet fitter',
  'curtain fitter',
  'blind fitter',
  'kitchen fitter',
  'bathroom fitter',

  // ── Carpentry & woodwork ─────────────────────────────────────────────────
  'carpenter',
  'joiner',
  'staircase specialist',
  'bespoke furniture maker',
  'french polisher',

  // ── Outdoor & grounds ────────────────────────────────────────────────────
  'gardener',
  'landscaper',
  'garden designer',
  'tree surgeon',
  'arborist',
  'fencer',
  'driveway installer',
  'resin driveway installer',
  'block paving installer',
  'tarmac contractor',
  'patio installer',
  'decking installer',
  'artificial grass installer',
  'garden room builder',
  'summer house installer',
  'pergola installer',
  'pond specialist',
  'lawn care service',

  // ── Heating/cooling & energy ─────────────────────────────────────────────
  'air conditioning installer',
  'air conditioning service',
  'log burner installer',
  'wood burning stove installer',
  'stair lift installer',
  'EPC assessor',

  // ── Scaffolding, access & clearance ──────────────────────────────────────
  'scaffolding company',
  'skip hire',
  'rubbish removal',
  'junk removal',
  'house clearance',

  // ── Specialist building services ─────────────────────────────────────────
  'handyman',
  'property maintenance',
  'damp proofing specialist',
  'asbestos removal',
  'mould treatment specialist',
  'pest control',
  'drain specialist',
  'septic tank specialist',
  'flood damage restoration',

  // ── Cleaning & domestic services ─────────────────────────────────────────
  'domestic cleaner',
  'end of tenancy cleaner',
  'oven cleaner',
  'carpet cleaner',
  'upholstery cleaner',
  'pressure washing service',
  'bin cleaner',
  'ironing service',
  'laundry service',
  'dry cleaner',
  'laundrette',

  // ── Removals & storage ───────────────────────────────────────────────────
  'removal company',
  'man and van',
  'storage facility',
  'furniture delivery',

  // ── Automotive ───────────────────────────────────────────────────────────
  'car garage',
  'mot centre',
  'car body repair',
  'mobile mechanic',
  'car wash',
  'mobile car valeter',
  'car detailing',
  'tyre fitting',
  'windscreen repair',
  'paintless dent repair',
  'alloy wheel refurbishment',
  'vehicle wrapping',
  'car air conditioning service',
  'ECU remapping',
  'motorcycle garage',
  'classic car restoration',
  'caravan servicing',
  'campervan conversion',

  // ── Food & hospitality: takeaways & cafes ────────────────────────────────
  'fish and chip shop',
  'pizza takeaway',
  'kebab shop',
  'chicken shop',
  'sandwich shop',
  'cafe',
  'specialty coffee shop',
  'bubble tea shop',
  'juice bar',
  'tea room',
  'bakery',
  'artisan bakery',
  'patisserie',
  'pie shop',
  'pasty shop',
  'sweet shop',
  'ice cream parlour',
  'mobile caterer',
  'food van',
  'ice cream van',

  // ── Food & hospitality: restaurants by cuisine ───────────────────────────
  'indian restaurant',
  'bangladeshi restaurant',
  'pakistani restaurant',
  'chinese restaurant',
  'thai restaurant',
  'vietnamese restaurant',
  'japanese restaurant',
  'korean restaurant',
  'italian restaurant',
  'greek restaurant',
  'turkish restaurant',
  'lebanese restaurant',
  'persian restaurant',
  'moroccan restaurant',
  'spanish restaurant',
  'mexican restaurant',
  'caribbean restaurant',
  'polish restaurant',
  'portuguese restaurant',
  'nepalese restaurant',
  'malaysian restaurant',
  'ramen restaurant',
  'sushi restaurant',
  'tapas bar',
  'steakhouse',
  'seafood restaurant',
  'vegan restaurant',
  'vegetarian restaurant',

  // ── Food & hospitality: pubs & bars ──────────────────────────────────────
  'pub',
  'gastropub',
  'wine bar',
  'cocktail bar',
  'real ale pub',
  'craft brewery',
  'microbrewery',

  // ── Food & hospitality: specialist retail ────────────────────────────────
  'delicatessen',
  'farm shop',
  'butcher',
  'halal butcher',
  'fishmonger',
  'greengrocer',
  'cheese shop',
  'wine merchant',
  'health food shop',
  'home baker',
  'cake maker',
  'wedding cake maker',
  'private chef',
  'meal prep delivery',
  'hog roast caterer',
  'afternoon tea caterer',

  // ── Accommodation ────────────────────────────────────────────────────────
  'bed and breakfast',
  'guest house',
  'glamping site',
  'farm stay',
  'holiday let management',
  'self catering accommodation',

  // ── Health & wellness ────────────────────────────────────────────────────
  'massage therapist',
  'osteopath',
  'chiropractor',
  'physiotherapist',
  'sports therapist',
  'sports injury clinic',
  'hypnotherapist',
  'nutritionist',
  'podiatrist',
  'audiologist',
  'counsellor',
  'psychotherapist',
  'CBT therapist',
  'life coach',
  'personal trainer',
  'personal training studio',
  'yoga instructor',
  'yoga studio',
  'pilates instructor',
  'pilates studio',
  'acupuncturist',
  'reflexologist',
  'reiki practitioner',
  'aromatherapist',
  'herbalist',
  'homeopath',
  'naturopath',
  'mindfulness teacher',
  'weight loss clinic',

  // ── Fitness & sport ──────────────────────────────────────────────────────
  'boxing gym',
  'martial arts club',
  'karate club',
  'taekwondo club',
  'kickboxing club',
  'judo club',
  'CrossFit gym',
  'dance studio',
  'gymnastics club',
  'swim school',
  'tennis coach',
  'golf coach',
  'running coach',
  'cycling coach',

  // ── Beauty & grooming ────────────────────────────────────────────────────
  'hairdresser',
  'barber',
  'beauty salon',
  'nail salon',
  'tattoo studio',
  'mobile hairdresser',
  'mobile beauty therapist',
  'mobile nail technician',
  'tanning salon',
  'waxing salon',
  'spray tan salon',
  'makeup artist',
  'bridal makeup artist',
  'hair extensions specialist',
  'lash technician',
  'brow specialist',
  'microblading artist',
  'permanent makeup artist',
  'aesthetics clinic',
  'skin clinic',
  'laser hair removal clinic',
  'teeth whitening clinic',

  // ── Animal services ──────────────────────────────────────────────────────
  'dog groomer',
  'mobile dog groomer',
  'dog walker',
  'dog trainer',
  'dog day care',
  'dog boarding kennels',
  'pet sitter',
  'cat sitter',
  'cattery',
  'mobile vet',
  'farrier',
  'horse riding school',
  'independent pet shop',

  // ── Childcare & education ────────────────────────────────────────────────
  'childminder',
  'nursery',
  'private tutor',
  'piano teacher',
  'guitar teacher',
  'singing teacher',
  'music teacher',
  'art teacher',
  'drama teacher',
  'dance teacher',
  'swimming coach',
  'sports coach',
  'language tutor',
  'coding tutor',
  'driving instructor',
  'motorcycle instructor',

  // ── Creative & skilled trades ────────────────────────────────────────────
  'photographer',
  'videographer',
  'wedding photographer',
  'wedding videographer',
  'newborn photographer',
  'product photographer',
  'graphic designer',
  'illustrator',
  'web designer',
  'web developer',
  'app developer',
  'recording studio',
  'podcast studio',
  'jeweller',
  'furniture maker',
  'furniture restorer',
  'upholsterer',
  'seamstress',
  'tailor',
  'alterations service',
  'cobbler',
  'sign maker',
  'engraver',
  'calligrapher',
  'picture framer',
  'local printer',
  'potter',
  'stained glass artist',
  'blacksmith',

  // ── Repairs ──────────────────────────────────────────────────────────────
  'computer repair',
  'phone repair',
  'appliance repair',
  'bicycle repair',
  'watch repairer',
  'tv repair',
  'instrument repair',
  'jewellery repair',

  // ── Professional services ────────────────────────────────────────────────
  'accountant',
  'bookkeeper',
  'tax advisor',
  'payroll service',
  'mortgage broker',
  'independent financial advisor',
  'financial planner',
  'insurance broker',
  'solicitor',
  'will writer',
  'conveyancer',
  'planning consultant',
  'architect',
  'architectural technologist',
  'building surveyor',
  'quantity surveyor',
  'party wall surveyor',
  'interior designer',
  'independent estate agent',
  'letting agent',
  'property management',
  'hr consultant',
  'health and safety consultant',
  'it support',
  'it consultant',
  'website designer',
  'social media manager',
  'marketing consultant',
  'SEO consultant',
  'virtual assistant',
  'business coach',
  'copywriter',
  'translation service',
  'career coach',
  'cv writing service',

  // ── Events & entertainment ───────────────────────────────────────────────
  'wedding florist',
  'florist',
  'events florist',
  'wedding planner',
  'events planner',
  'wedding caterer',
  'event caterer',
  'wedding car hire',
  'marquee hire',
  'photo booth hire',
  'bouncy castle hire',
  'mobile bar hire',
  'casino night hire',
  'toastmaster',
  'celebrant',
  'mobile dj',
  'live musician',
  'magician',
  'caricaturist',
  'party entertainer',
  'face painter',
  'balloon artist',
  'singing waiters',
  'drone operator',

  // ── Transport ────────────────────────────────────────────────────────────
  'private hire taxi',
  'chauffeur service',
  'airport transfer',
  'minibus hire',
  'courier service',

  // ── Hire & specialist ────────────────────────────────────────────────────
  'tool hire',
  'equipment hire',

  // ── Retail & service units ───────────────────────────────────────────────
  'newsagent',
  'off licence',
  'independent pharmacy',
  'independent optician',
  'dental practice',
  'antique shop',
  'antique dealer',
  'bookshop',
  'record shop',
  'gift shop',
  'florist shop',
  'garden centre',
  'hardware store',
  'cycle shop',

  // ── Specialist UK services ───────────────────────────────────────────────
  'funeral director',
  'monumental mason',
  'independent travel agent',
  'pawn shop',
  'key cutter',

  // ── Leisure & experience ─────────────────────────────────────────────────
  'escape room',
  'soft play centre',
  'indoor climbing gym',
  'cookery school',
];
