// Geographic expansion order — Edinburgh outward.
// The pipeline runner works through this list in order,
// completing all categories for each area before moving to the next.
// Locations must exist in seeds/locations.js to have queue items.

export const expansionOrder = [
  // ── Ring 0: Edinburgh ────────────────────────────────────────────────────
  'Edinburgh',

  // ── Ring 1: Edinburgh suburbs (0–15km) ───────────────────────────────────
  'Musselburgh',
  'Dalkeith',
  'Bonnyrigg',
  'Loanhead',
  'Penicuik',
  'Gorebridge',
  'Tranent',
  'South Queensferry',
  'Broxburn',

  // ── Ring 2: Lothians & Fife (15–40km) ────────────────────────────────────
  'Haddington',
  'Dunbar',
  'North Berwick',
  'Bathgate',
  'Armadale',
  'Linlithgow',
  'Livingston',
  'Dunfermline',
  'Kirkcaldy',
  'Glenrothes',

  // ── Ring 3: Central Scotland (40–80km) ───────────────────────────────────
  'Falkirk',
  'Stirling',
  'Cumbernauld',
  'Glasgow',
  'Perth',
  'St Andrews',

  // ── Ring 4: West & Ayrshire ───────────────────────────────────────────────
  'Motherwell',
  'Hamilton',
  'East Kilbride',
  'Airdrie',
  'Coatbridge',
  'Paisley',
  'Greenock',
  'Port Glasgow',
  'Dumbarton',
  'Clydebank',
  'Kilmarnock',
  'Ayr',
  'Irvine',

  // ── Ring 5: Dundee, Tayside, Northeast ───────────────────────────────────
  'Dundee',
  'Arbroath',
  'Montrose',
  'Forfar',
  'Brechin',
  'Stonehaven',
  'Aberdeen',
  'Peterhead',
  'Fraserburgh',
  'Elgin',

  // ── Ring 6: Highlands & far north ────────────────────────────────────────
  'Inverness',
  'Forres',
  'Nairn',
  'Dingwall',
  'Tain',
  'Fort William',
  'Oban',
  'Thurso',
  'Wick',
  'Dumfries',

  // ── Northern England (south from Scottish border) ─────────────────────────
  'Newcastle upon Tyne',
  'Gateshead',
  'Sunderland',
  'Middlesbrough',
  'Carlisle',
  'Lancaster',
  'York',
  'Harrogate',
  'Leeds',
  'Bradford',
  'Wakefield',
  'Huddersfield',
  'Halifax',
  'Sheffield',
  'Barnsley',
  'Doncaster',
  'Rotherham',
  'Manchester',
  'Salford',
  'Bolton',
  'Wigan',
  'Preston',
  'Blackburn',
  'Burnley',
  'Liverpool',
  'Birkenhead',
  'Warrington',
  'Stockport',

  // ── Midlands ──────────────────────────────────────────────────────────────
  'Nottingham',
  'Leicester',
  'Derby',
  'Stoke-on-Trent',
  'Coventry',
  'Birmingham',
  'Wolverhampton',

  // ── East & South ──────────────────────────────────────────────────────────
  'Peterborough',
  'Cambridge',
  'Norwich',
  'Ipswich',
  'Milton Keynes',
  'Northampton',
  'Oxford',
  'Bristol',
  'Cardiff',
  'Swansea',
  'Southampton',
  'Portsmouth',
  'Brighton',
  'London',
];
