// UK towns, cities, and sub-areas for Found Local + Already Done pipeline.
// Covers all significant population centres (roughly 5,000+) plus sub-areas
// of major cities for hyper-local directory coverage.
// Scotland listed Edinburgh-outward; rest of UK roughly by region.

export const locations = [

  // ── Scotland: Edinburgh & sub-areas ──────────────────────────────────────
  'Edinburgh',
  'Leith', 'Portobello', 'Morningside', 'Stockbridge', 'Newington',
  'Corstorphine', 'Gorgie', 'Dalry', 'Marchmont', 'Bruntsfield',
  'Liberton', 'Gilmerton', 'Craigmillar', 'Newhaven Edinburgh', 'Colinton',
  'Currie', 'Balerno', 'Restalrig', 'Granton', 'Muirhouse',
  'Pilton Edinburgh', 'Silverknowes', 'Juniper Green', 'Slateford',
  'Stenhouse', 'Longstone Edinburgh', 'Pilrig', 'Bonnington Edinburgh',
  // Edinburgh suburbs
  'Musselburgh', 'Dalkeith', 'Bonnyrigg', 'Penicuik', 'Loanhead',
  'Gorebridge', 'Tranent', 'Haddington', 'North Berwick', 'Dunbar',
  'South Queensferry', 'Broxburn', 'Bathgate', 'Armadale', 'Linlithgow',
  'Livingston',

  // ── Scotland: Fife & Central ──────────────────────────────────────────────
  'Dunfermline', 'Kirkcaldy', 'Glenrothes', 'Leven', 'Buckhaven',
  'Cupar', 'St Andrews', 'Anstruther', 'Pittenweem',
  'Falkirk', 'Grangemouth', "Bo'ness", 'Stirling', 'Alloa', 'Clackmannan',
  'Cumbernauld', 'Kirkintilloch', 'Bishopbriggs',

  // ── Scotland: Glasgow & sub-areas ────────────────────────────────────────
  'Glasgow',
  'Shawlands', 'Partick', 'Govan', 'Maryhill', 'Springburn',
  'Dennistoun', 'Bridgeton', 'Pollokshaws', 'Pollokshields',
  'Anniesland', 'Scotstoun', 'Whiteinch', 'Yoker',
  'Kelvinside', 'Hyndland', 'Broomhill Glasgow', 'Thornwood',
  'Cardonald', 'Penilee', 'Hillington', 'Drumoyne',
  'Mount Florida', 'Cathcart', 'Battlefield Glasgow',
  'Govanhill', 'Toryglen',
  'Dalmarnock', 'Parkhead', 'Shettleston', 'Tollcross Glasgow',
  'Riddrie', 'Hogganfield', 'Robroyston',
  'Possilpark', 'Milton Glasgow', 'Lambhill', 'Summerston',
  'Drumchapel', 'Knightswood', 'Temple Glasgow',
  // Glasgow suburbs
  'Bearsden', 'Milngavie', 'Newton Mearns', 'Giffnock', 'Clarkston',
  'Rutherglen', 'Cambuslang', 'Blantyre', 'Uddingston',
  'Motherwell', 'Hamilton', 'East Kilbride', 'Lanark', 'Larkhall',
  'Airdrie', 'Coatbridge', 'Bellshill', 'Wishaw', 'Shotts',
  'Paisley', 'Renfrew', 'Johnstone', 'Barrhead',
  'Greenock', 'Port Glasgow', 'Dumbarton', 'Clydebank', 'Helensburgh',
  'Kilmarnock', 'Ayr', 'Irvine', 'Troon', 'Prestwick', 'Saltcoats',
  'Largs', 'Ardrossan', 'Stevenston',

  // ── Scotland: Tayside & Northeast ────────────────────────────────────────
  'Perth',
  'Dundee',
  'Broughty Ferry', 'Stobswell', 'Lochee', 'Menzieshill',
  'Hilltown', 'Douglas Dundee', 'Kirkton Dundee', 'Ardler', 'Linlathen',
  'Arbroath', 'Montrose', 'Brechin',
  'Forfar', 'Kirriemuir', 'Blairgowrie', 'Crieff', 'Pitlochry',
  'Stonehaven',
  'Aberdeen',
  'Torry', 'Bridge of Don', 'Tillydrone', 'Woodside Aberdeen',
  'Mastrick', 'Northfield Aberdeen', 'Cove Bay', 'Dyce',
  'Hilton Aberdeen', 'Kittybrewster', 'Garthdee', 'Mannofield',
  'Danestone', 'Bucksburn', 'Kingswells',
  'Banchory', 'Inverurie', 'Ellon', 'Fraserburgh', 'Peterhead',
  'Turriff', 'Huntly', 'Keith', 'Buckie', 'Elgin', 'Forres',
  'Nairn', 'Aviemore',

  // ── Scotland: Highlands & Islands ────────────────────────────────────────
  'Inverness',
  'Crown Inverness', 'Inshes', 'Merkinch',
  'Dingwall', 'Tain', 'Invergordon', 'Alness',
  'Fort William', 'Oban', 'Dunoon',
  'Thurso', 'Wick', 'Dornoch', 'Golspie', 'Brora',
  'Stornoway', 'Portree',

  // ── Scotland: South ───────────────────────────────────────────────────────
  'Dumfries', 'Stranraer', 'Newton Stewart', 'Castle Douglas',
  'Galashiels', 'Hawick', 'Jedburgh', 'Selkirk', 'Peebles',
  'Kelso', 'Berwick-upon-Tweed',

  // ── Northern Ireland ──────────────────────────────────────────────────────
  'Belfast',
  'Ballyhackamore', 'Andersonstown', 'Finaghy',
  'Dunmurry', 'Newtownbreda', 'Stranmillis Belfast',
  'Ballynafeigh', 'Lisburn Road Belfast',
  'Shankill Belfast', 'Cregagh', 'Stormont',
  'Sydenham Belfast',
  'Derry',
  'Waterside Derry', 'Bogside', 'Creggan',
  'Lisburn', 'Newtownabbey', 'Bangor', 'Newry', 'Armagh',
  'Ballymena', 'Antrim', 'Coleraine', 'Omagh', 'Enniskillen',
  'Dungannon', 'Cookstown', 'Magherafelt', 'Limavady', 'Strabane',
  'Portadown', 'Lurgan', 'Craigavon', 'Banbridge', 'Downpatrick',
  'Newtownards', 'Holywood', 'Carrickfergus', 'Larne', 'Ballymoney',
  'Portstewart', 'Portrush', 'Ballycastle', 'Dromore',
  'Ballyclare', 'Greenisland', 'Whitehead',

  // ── Northeast England ─────────────────────────────────────────────────────
  'Newcastle upon Tyne',
  'Jesmond', 'Gosforth', 'Byker', 'Fenham', 'Benwell',
  'Elswick', 'Heaton Newcastle', 'Walker Newcastle', 'Ouseburn',
  'Westgate Newcastle', 'Lemington', 'Kenton Newcastle',
  'Gateshead',
  'Dunston', 'Felling', 'Low Fell', 'Lobley Hill', 'Whickham',
  'Blaydon', 'Birtley', 'Ryton',
  'Sunderland',
  'Pallion', 'Hendon Sunderland', 'Monkwearmouth', 'Pennywell Sunderland',
  'Southwick Sunderland', 'Grindon', 'Hylton Castle',
  'Middlesbrough',
  'Linthorpe', 'Acklam', 'Coulby Newham', 'Marton Middlesbrough',
  'Nunthorpe', 'Eston', 'Normanby',
  'Hartlepool', 'Stockton-on-Tees',
  'Billingham', 'Thornaby', 'Ingleby Barwick', 'Fairfield Stockton',
  'Darlington',
  'Cockerton', 'Haughton-le-Skerne',
  'Durham',
  'Framwellgate Moor', 'Gilesgate', 'Nevilles Cross', 'Pity Me',
  'Chester-le-Street', 'Stanley', 'Consett', 'Bishop Auckland',
  'Newton Aycliffe', 'Spennymoor', 'Shildon',
  'South Shields', 'Jarrow', 'Hebburn', 'Houghton-le-Spring',
  'Washington', 'Peterlee', 'Seaham',
  'Whitley Bay', 'Tynemouth', 'Wallsend', 'Longbenton',
  'Cramlington', 'Blyth', 'Morpeth', 'Ashington', 'Bedlington',
  'Hexham', 'Prudhoe', 'Corbridge',
  'Scarborough', 'Whitby', 'Filey', 'Bridlington',
  'Driffield', 'Beverley', 'Hornsea',

  // ── Northwest England ─────────────────────────────────────────────────────
  'Liverpool',
  'Wavertree', 'Toxteth', 'Edge Hill Liverpool',
  'Old Swan', 'West Derby', 'Childwall', 'Allerton Liverpool',
  'Aigburth', 'Garston', 'Speke', 'Woolton', 'Mossley Hill',
  'Anfield', 'Walton Liverpool', 'Kirkdale', 'Tuebrook',
  'Clubmoor', 'Norris Green', 'Fazakerley', 'Croxteth',
  'Bootle', 'Crosby', 'Formby', 'Southport', 'Kirkby',
  'Huyton', 'Prescot', 'St Helens', 'Newton-le-Willows',
  'Birkenhead', 'Wallasey', 'Ellesmere Port', 'Neston',
  'Chester', 'Northwich', 'Winsford', 'Middlewich',
  'Widnes', 'Runcorn', 'Frodsham', 'Warrington',
  'Manchester',
  'Hulme', 'Gorton', 'Levenshulme', 'Rusholme', 'Moss Side',
  'Whalley Range', 'Burnage', 'Longsight', 'Ardwick', 'Ancoats',
  'Chorlton', 'Didsbury', 'Withington', 'Fallowfield',
  'Wythenshawe', 'Benchill', 'Baguley', 'Northenden', 'Sharston',
  'Openshaw', 'Beswick', 'Moston', 'Newton Heath', 'Collyhurst',
  'Harpurhey', 'Miles Platting', 'Clayton Manchester',
  'Salford', 'Ordsall', 'Pendleton Salford', 'Weaste', 'Langworthy',
  'Eccles', 'Irlam', 'Worsley', 'Swinton',
  'Stretford', 'Urmston', 'Sale', 'Altrincham',
  'Stockport', 'Cheadle', 'Bramhall', 'Hazel Grove', 'Marple',
  'Macclesfield', 'Wilmslow', 'Knutsford', 'Congleton', 'Crewe',
  'Nantwich', 'Sandbach',
  'Bolton',
  'Farnworth', 'Westhoughton', 'Horwich', 'Leigh',
  'Halliwell', 'Deane', 'Breightmet', 'Heaton Bolton',
  'Wigan',
  'Hindley', 'Ince-in-Makerfield', 'Abram', 'Atherton',
  'Skelmersdale', 'Ormskirk',
  'Bury', 'Ramsbottom', 'Heywood', 'Middleton', 'Rochdale',
  'Oldham', 'Failsworth', 'Droylsden', 'Ashton-under-Lyne',
  'Stalybridge', 'Hyde', 'Glossop', 'Denton',
  'Blackburn',
  'Accrington', 'Darwen', 'Rawtenstall', 'Haslingden',
  'Wensley Fold', 'Mill Hill Blackburn', 'Ewood', 'Billinge End',
  'Nelson', 'Colne', 'Clitheroe', 'Burnley', 'Padiham',
  'Preston',
  'Ribbleton', 'Ingol', 'Fulwood', 'Ashton Preston',
  'Leyland', 'Chorley',
  'Blackpool', 'Lytham St Annes', 'Fleetwood', 'Poulton-le-Fylde',
  'Lancaster', 'Morecambe', 'Heysham', 'Carnforth',
  'Carlisle', 'Penrith', 'Workington', 'Whitehaven', 'Barrow-in-Furness',
  'Kendal', 'Windermere', 'Ulverston',

  // ── Yorkshire ─────────────────────────────────────────────────────────────
  'Leeds',
  'Headingley', 'Chapel Allerton', 'Harehills', 'Roundhay',
  'Meanwood', 'Hyde Park Leeds', 'Burley Leeds', 'Kirkstall',
  'Armley', 'Holbeck', 'Hunslet', 'Beeston Leeds',
  'Seacroft', 'Cross Gates', 'Bramley Leeds', 'Wortley',
  'Morley', 'Pudsey', 'Horsforth', 'Garforth', 'Rothwell',
  'Wetherby', 'Otley', 'Yeadon', 'Guiseley',
  'Bradford',
  'Manningham', 'Heaton Bradford', 'Great Horton', 'Wibsey',
  'Buttershaw', 'Thornton Bradford', 'Clayton Bradford',
  'Eccleshill', 'Idle', 'Greengates',
  'Shipley', 'Bingley', 'Keighley', 'Ilkley',
  'Skipton', 'Settle', 'Harrogate', 'Knaresborough', 'Ripon',
  'York',
  'Acomb', 'Fulford', 'Heslington', 'Huntington York',
  'Selby', 'Tadcaster',
  'Wakefield',
  'Ossett', 'Horbury', 'Normanton', 'Castleford',
  'Pontefract', 'Knottingley', 'Featherstone',
  'Huddersfield',
  'Lindley', 'Moldgreen', 'Dalton Huddersfield',
  'Dewsbury', 'Batley', 'Heckmondwike',
  'Halifax',
  'Brighouse', 'Elland', 'Sowerby Bridge', 'Hebden Bridge',
  'Todmorden',
  'Sheffield',
  'Hillsborough', 'Walkley', 'Crookes', 'Ecclesall', 'Nether Edge',
  "Hunter's Bar", 'Broomhill Sheffield', 'Attercliffe', 'Darnall',
  'Woodseats', 'Gleadless', 'Burngreave', 'Firth Park', 'Southey',
  'Handsworth Sheffield', 'Beighton', 'Mosborough', 'Hackenthorpe',
  'Stannington', 'Loxley', 'Sharrow', 'Heeley',
  'Rotherham',
  'Maltby', 'Wath upon Dearne', 'Rawmarsh', 'Swinton Rotherham',
  'Barnsley',
  'Wombwell', 'Hoyland', 'Darfield', 'Goldthorpe', 'Thurnscoe',
  'Penistone', 'Cudworth', 'Grimethorpe',
  'Doncaster',
  'Balby', 'Bentley Doncaster', 'Bessacarr', 'Wheatley Hills',
  'Mexborough', 'Conisbrough', 'Retford', 'Gainsborough',

  // ── East Midlands ─────────────────────────────────────────────────────────
  'Nottingham',
  'The Meadows', 'Sherwood', 'Mapperley', 'Bulwell', 'Aspley',
  'Lenton', 'Radford Nottingham', 'Forest Fields', "St Ann's Nottingham",
  'Sneinton', 'Old Basford', 'New Basford',
  'Wollaton', 'Bilborough', 'Clifton Nottingham',
  'West Bridgford', 'Beeston', 'Arnold', 'Carlton',
  'Hucknall', 'Kirkby in Ashfield', 'Mansfield', 'Sutton in Ashfield',
  'Long Eaton', 'Ilkeston', 'Stapleford',
  'Worksop',
  'Derby',
  'Alvaston', 'Mickleover', 'Littleover', 'Allestree', 'Chellaston',
  'Normanton Derby', 'Spondon', 'Chaddesden', 'Mackworth', 'Oakwood Derby',
  'Belper', 'Ripley', 'Alfreton', 'Matlock', 'Bakewell',
  'Buxton', 'Chapel-en-le-Frith', 'Whaley Bridge',
  'Chesterfield', 'Dronfield', 'Staveley', 'Eckington',
  'Leicester',
  'Oadby', 'Wigston', 'Blaby', 'Braunstone', 'Beaumont Leys',
  'Humberstone', 'Evington', 'Clarendon Park', 'Knighton', 'Aylestone',
  'Belgrave', 'Rushey Mead', 'Hamilton Leicester', 'Westcotes',
  'Spinney Hills', 'New Parks', 'Rowley Fields', 'Glen Parva',
  'Loughborough', 'Melton Mowbray', 'Hinckley', 'Coalville',
  'Nuneaton', 'Bedworth',
  'Northampton',
  'Abington', 'Kingsthorpe', 'Duston', 'Boothville',
  'Kettering', 'Corby', 'Wellingborough',
  'Rushden', 'Daventry', 'Towcester',
  'Lincoln', 'Grantham', 'Stamford', 'Sleaford', 'Skegness',
  'Spalding', 'Boston', 'Louth', 'Grimsby', 'Cleethorpes', 'Scunthorpe',

  // ── West Midlands ─────────────────────────────────────────────────────────
  'Birmingham',
  'Erdington', 'Sutton Coldfield', 'Kings Heath', 'Moseley',
  'Selly Oak', 'Harborne', 'Handsworth', 'Perry Barr',
  'Aston', 'Small Heath', 'Sparkbrook', 'Sparkhill',
  'Bordesley Green', 'Bournville', 'Stirchley', 'Edgbaston',
  'Ladywood', 'Nechells', 'Yardley', 'Acocks Green',
  'Hall Green', 'Great Barr', 'Castle Bromwich', 'Stechford',
  'Tyseley', 'Sheldon', 'Hodge Hill', 'Ward End',
  'Kingstanding', 'Oscott', 'Boldmere', 'Streetly',
  'Northfield Birmingham', 'Longbridge', 'Rubery',
  'Bartley Green', 'Weoley Castle', 'Kings Norton',
  'Coventry',
  'Earlsdon', 'Coundon', 'Foleshill', 'Radford Coventry',
  'Stoke Coventry', 'Tile Hill', 'Binley', 'Canley',
  'Cheylesmore', 'Whitley Coventry', 'Wyken', 'Walsgrave',
  'Rugby', 'Kenilworth', 'Leamington Spa',
  'Warwick', 'Stratford-upon-Avon',
  'Wolverhampton',
  'Bilston', 'Wednesfield', 'Willenhall',
  'Fallings Park', 'Fordhouses', 'Penn', 'Tettenhall',
  'Bushbury', 'Low Hill', 'Heath Town', 'Oxley',
  'Walsall',
  'Bloxwich', 'Pelsall', 'Brownhills', 'Aldridge',
  'West Bromwich',
  'Tipton', 'Wednesbury', 'Great Bridge', 'Oldbury',
  'Solihull',
  'Shirley Solihull', 'Olton', 'Knowle Solihull', 'Dorridge',
  'Dudley',
  'Netherton', 'Kingswinford', 'Sedgley', 'Coseley',
  'Stourbridge', 'Halesowen', 'Brierley Hill',
  'Kidderminster', 'Bromsgrove', 'Redditch',
  'Telford',
  'Dawley', 'Madeley Telford', 'Oakengates', 'Wellington Shropshire',
  'Shrewsbury', 'Oswestry', 'Market Drayton',
  'Stoke-on-Trent',
  'Hanley', 'Burslem', 'Longton', 'Fenton Stoke', 'Tunstall', 'Trentham',
  'Newcastle-under-Lyme', 'Kidsgrove', 'Leek',
  'Stafford', 'Cannock', 'Tamworth', 'Lichfield', 'Burton upon Trent',
  'Uttoxeter', 'Rugeley',
  'Worcester', 'Pershore', 'Malvern', 'Droitwich',
  'Hereford', 'Ross-on-Wye', 'Ledbury',
  'Ludlow', 'Whitchurch', 'Newport Shropshire',
  'Evesham',

  // ── East of England ───────────────────────────────────────────────────────
  'Peterborough',
  'Bretton', 'Dogsthorpe', 'Werrington', 'Stanground', 'Orton Peterborough',
  'Eye Peterborough', 'Paston Peterborough', 'Longthorpe',
  'March', 'Wisbech', 'Ely', 'Huntingdon',
  'St Ives Cambridgeshire', 'Ramsey',
  'Cambridge',
  'Arbury', 'Chesterton Cambridge', 'Cherry Hinton', 'Newnham Cambridge',
  'Queen Ediths', 'Trumpington', 'Abbey Cambridge', 'Coleridge Cambridge',
  'Bury St Edmunds', 'Ipswich',
  'Stoke Ipswich', 'Rushmere', 'Whitton Ipswich', 'Ravenswood',
  'Chantry Ipswich', 'Gainsborough Ipswich',
  'Sudbury', 'Haverhill',
  'Newmarket', 'Thetford',
  'Norwich',
  'Eaton Norwich', 'Thorpe St Andrew', 'Hellesdon', 'Costessey',
  'Bowthorpe', 'Catton', 'Sprowston',
  'Dereham', 'Wymondham', 'Attleborough', 'Fakenham',
  "King's Lynn", 'Hunstanton', 'Swaffham',
  'Great Yarmouth', 'Lowestoft', 'Beccles', 'Bungay',
  'Colchester',
  'Greenstead', 'Mile End Colchester', 'Shrub End', 'Lexden',
  'Chelmsford',
  'Moulsham', 'Widford', 'Broomfield',
  'Basildon',
  'Laindon', 'Pitsea', 'Vange',
  'Southend-on-Sea',
  'Leigh-on-Sea', 'Westcliff-on-Sea', 'Shoeburyness', 'Thorpe Bay',
  'Harlow', 'Brentwood', 'Billericay', 'Wickford',
  'Clacton-on-Sea', 'Frinton-on-Sea',
  'Stevenage', 'Hitchin', 'Letchworth', 'Baldock', 'Royston',
  'Hertford', 'Ware', 'Hoddesdon', 'Broxbourne',
  'Watford', 'Hemel Hempstead', 'St Albans', 'Hatfield',
  'Welwyn Garden City', 'Harpenden',
  'Luton',
  'Leagrave', 'Bury Park Luton', 'Stopsley',
  'Dunstable', 'Leighton Buzzard', 'Biggleswade', 'Bedford',
  'Kempston',
  'Milton Keynes', 'Bletchley', 'Wolverton', 'Newport Pagnell',

  // ── London: Inner North ───────────────────────────────────────────────────
  'Camden', 'Hampstead', 'Belsize Park', 'Kentish Town', 'Archway',
  'Highgate', 'Muswell Hill', 'Crouch End', 'Hornsey',
  'Islington', 'Angel Islington', 'Holloway', 'Highbury', 'Finsbury Park',
  'Stoke Newington', 'Stamford Hill', 'Dalston', 'Hackney',
  'Clapton', 'Homerton', 'Hackney Wick', 'Shoreditch',
  'Haringey', 'Tottenham', 'Wood Green', 'Bounds Green',
  'Palmers Green', 'Bowes Park', 'Edmonton', 'Winchmore Hill',
  'Enfield', 'Waltham Cross', 'Enfield Town', 'Southgate',
  'Barnet', 'Finchley', 'Edgware', 'Mill Hill', 'Hendon',
  'Golders Green', 'Childs Hill', 'Cricklewood',

  // ── London: Inner East ────────────────────────────────────────────────────
  'Tower Hamlets', 'Bethnal Green', 'Bow London', 'Stepney',
  'Whitechapel', 'Mile End', 'Poplar', 'Canary Wharf', 'Limehouse',
  'Walthamstow', 'Leyton', 'Leytonstone', 'Chingford',
  'Stratford London', 'West Ham', 'Forest Gate', 'Manor Park',
  'Barking', 'Dagenham',
  'Ilford', 'Romford', 'Hornchurch', 'Upminster',
  'Plaistow', 'Canning Town',
  'Seven Kings', 'Goodmayes',
  'Harold Wood', 'Gidea Park',

  // ── London: Inner South ───────────────────────────────────────────────────
  'Southwark', 'Borough London', 'Bermondsey', 'Elephant and Castle',
  'Lambeth', 'Kennington', 'Stockwell', 'Vauxhall',
  'Brixton', 'Tulse Hill', 'Herne Hill',
  'Peckham', 'New Cross', 'Deptford',
  'Lewisham', 'Catford', 'Brockley', 'Lee London', 'Hither Green',
  'Forest Hill', 'Sydenham', 'Crystal Palace',
  'Greenwich', 'Woolwich', 'Eltham', 'Blackheath',
  'Bromley', 'Beckenham', 'Penge', 'Orpington', 'Chislehurst',
  'Croydon', 'Thornton Heath', 'Norwood', 'Addiscombe',
  'Sutton', 'Cheam', 'Worcester Park', 'Wallington',
  'Kingston upon Thames', 'Richmond', 'Twickenham', 'Teddington', 'Putney',
  'Wandsworth', 'Tooting', 'Balham', 'Clapham', 'Streatham',
  'Earlsfield', 'Wimbledon', 'Merton',
  'Bexley', 'Erith', 'Crayford', 'Welling', 'Sidcup', 'Bexleyheath',

  // ── London: Inner West & Central ─────────────────────────────────────────
  'Westminster', 'Pimlico', 'Victoria London',
  'Marylebone', 'Maida Vale', 'Paddington', 'Bayswater',
  'Clerkenwell', 'Farringdon', 'Barbican',
  'Covent Garden', 'Soho', 'Fitzrovia',
  'Kensington', 'Notting Hill', 'Ladbroke Grove',
  "Shepherd's Bush", 'Holland Park',
  'Hammersmith', 'Fulham', 'Chelsea', 'Battersea',
  'Harrow', 'Wembley', 'Ealing', 'Acton', 'Hanwell',
  'Northolt', 'Greenford', 'Southall',
  'Hounslow', 'Feltham', 'Uxbridge', 'Hayes',
  'Staines-upon-Thames', 'Ashford Surrey',

  // ── South East England ────────────────────────────────────────────────────
  'Guildford', 'Woking', 'Camberley', 'Farnborough', 'Aldershot',
  'Farnham', 'Fleet', 'Basingstoke', 'Andover', 'Winchester',
  'Eastleigh', 'Fareham', 'Gosport',
  'Southampton',
  'Shirley Southampton', 'Bitterne', 'Millbrook Southampton',
  'Bassett', 'Freemantle', 'St Denys',
  'Sholing', 'Woolston', 'Thornhill Southampton', 'Lordswood',
  'Totton', 'Hedge End', 'Bursledon',
  'Portsmouth',
  'Southsea', 'Fratton', 'Cosham', 'Paulsgrove', 'Farlington',
  'North End Portsmouth', 'Hilsea',
  'Havant', 'Waterlooville', 'Petersfield',
  'Chichester', 'Bognor Regis', 'Littlehampton', 'Worthing',
  'Brighton',
  'Hove', 'Kemptown', 'Hanover Brighton', 'Fiveways Brighton',
  'Preston Park Brighton',
  'Lewes', 'Seaford', 'Newhaven',
  'Eastbourne', 'Hastings', 'Bexhill', 'Rye',
  'Battle', 'Hailsham', 'Uckfield', 'Crowborough',
  'East Grinstead', 'Crawley', 'Horsham', 'Haywards Heath',
  'Burgess Hill', 'Steyning',
  'Epsom', 'Redhill', 'Reigate', 'Dorking', 'Leatherhead',
  'Weybridge', 'Walton-on-Thames', 'Esher',
  'Sevenoaks', 'Tonbridge', 'Tunbridge Wells', 'Paddock Wood',
  'Maidstone', 'Sittingbourne', 'Faversham', 'Canterbury',
  'Whitstable', 'Herne Bay', 'Margate', 'Ramsgate', 'Deal',
  'Dover', 'Folkestone', 'Hythe', 'Ashford',
  'Chatham', 'Rochester', 'Gillingham', 'Gravesend', 'Dartford',

  // ── South West England ────────────────────────────────────────────────────
  'Bristol',
  'Clifton', 'Redland', 'Cotham', 'Stokes Croft', 'Montpelier',
  'St Werburghs', 'Easton Bristol', 'St George Bristol',
  'Bedminster', 'Southville', 'Knowle Bristol', 'Brislington',
  'Horfield', 'Bishopston', 'Westbury-on-Trym', 'Henleaze',
  'Filton', 'Patchway', 'Fishponds', 'Whitchurch Bristol',
  'Lawrence Weston', 'Avonmouth', 'Shirehampton',
  'Kingswood', 'Yate', 'Thornbury',
  'Bath',
  'Twerton', 'Oldfield Park Bath', 'Widcombe', 'Combe Down',
  'Keynsham', 'Radstock',
  'Gloucester',
  'Quedgeley', 'Kingsway Gloucester', 'Barnwood', 'Longlevens', 'Tuffley',
  'Cheltenham',
  'Leckhampton', 'Charlton Kings', 'Prestbury', 'Up Hatherley', 'Benhall',
  'Stroud', 'Cirencester', 'Tewkesbury',
  'Swindon',
  'Old Town Swindon', 'Walcot Swindon', 'Gorse Hill', 'Penhill',
  'Chippenham', 'Trowbridge', 'Devizes', 'Melksham',
  'Westbury', 'Warminster', 'Salisbury', 'Amesbury',
  'Weston-super-Mare',
  'Worle', 'Uphill', 'Kewstoke',
  'Clevedon', 'Portishead', 'Nailsea',
  'Bridgwater', 'Taunton',
  'Taunton East', 'Wellington Somerset', 'Norton Fitzwarren',
  'Yeovil', 'Chard', 'Ilminster',
  'Frome', 'Shepton Mallet', 'Wells', 'Glastonbury',
  'Minehead', 'Burnham-on-Sea',
  'Exeter',
  'Heavitree', 'Pinhoe', 'Whipton', 'St Thomas Exeter',
  'Exmouth', 'Sidmouth', 'Honiton', 'Axminster',
  'Tiverton', 'Crediton', 'Okehampton',
  'Plymouth',
  'Devonport', 'Stonehouse Plymouth', 'Mutley', 'Efford',
  'Plymstock', 'Plympton', 'Peverell', 'Lipson', 'Keyham',
  'Crownhill', 'Leigham', 'Ernesettle', 'St Budeaux',
  'Saltash', 'Torpoint',
  'Torquay', 'Paignton', 'Brixham', 'Totnes', 'Newton Abbot',
  'Dartmouth', 'Kingsbridge', 'Ivybridge',
  'Barnstaple', 'Bideford', 'Ilfracombe', 'South Molton',
  'Truro', 'Falmouth', 'Penryn', 'Helston',
  'Penzance', 'St Ives Cornwall', 'Newquay', 'Bodmin', 'Launceston',
  'Liskeard', 'St Austell', 'Camborne', 'Redruth',
  'Weymouth', 'Dorchester', 'Bridport', 'Sherborne',
  'Poole',
  'Canford Heath', 'Parkstone', 'Branksome',
  'Bournemouth',
  'Boscombe', 'Winton', 'Charminster Bournemouth', 'Westbourne Bournemouth',
  'Christchurch',

  // ── Wales ─────────────────────────────────────────────────────────────────
  'Cardiff',
  'Roath', 'Canton Cardiff', 'Pontcanna', 'Cathays', 'Splott',
  'Grangetown', 'Butetown', 'Riverside Cardiff', 'Llandaff',
  'Llandaff North', 'Whitchurch Cardiff', 'Rhiwbina',
  'Gabalfa', 'Adamsdown', 'Penylan', 'Heath Cardiff',
  'Lisvane', 'Rumney', 'Llanrumney', 'Pontprennau', 'Llanishen',
  'Newport Wales',
  'Bettws Newport', 'Pill Newport', 'Ringland Newport',
  'Liswerry', 'Alway Newport', 'Maindee', 'Rogerstone',
  'Cwmbran', 'Pontypool', 'Abergavenny', 'Monmouth',
  'Barry', 'Penarth', 'Dinas Powys',
  'Caerphilly', 'Bargoed', 'Ystrad Mynach',
  'Pontypridd', 'Porth', 'Tonypandy', 'Treorchy',
  'Merthyr Tydfil', 'Aberdare', 'Mountain Ash', 'Ferndale',
  'Bridgend', 'Maesteg', 'Porthcawl',
  'Neath', 'Port Talbot',
  'Swansea',
  'Sketty', 'Uplands Swansea', 'Morriston', 'Llansamlet',
  'Clydach', 'Fforestfach', 'Gorseinon',
  'Llanelli', 'Ammanford',
  'Carmarthen', 'Llandeilo', 'Llandovery',
  'Pembroke', 'Pembroke Dock', 'Haverfordwest', 'Milford Haven',
  'Tenby', 'Narberth', 'Fishguard',
  'Aberystwyth', 'Aberaeron', 'Cardigan',
  'Lampeter', 'Llandysul',
  'Wrexham',
  'Rhosllannerchrugog', 'Ruabon',
  'Mold', 'Buckley', 'Flint', 'Holywell', 'Rhyl',
  'Prestatyn', 'Colwyn Bay', 'Llandudno', 'Conwy', 'Abergele',
  'Bangor Gwynedd',
  'Bethesda', 'Llanfairfechan', 'Penmaenmawr',
  'Caernarfon', 'Porthmadog', 'Pwllheli',
  'Llangefni', 'Holyhead', 'Amlwch', 'Beaumaris',
  'Welshpool', 'Newtown Powys', 'Llandrindod Wells', 'Brecon',

  // ── Oxford / Reading corridor ─────────────────────────────────────────────
  'Oxford',
  'Cowley', 'Headington', 'Summertown Oxford', 'Jericho Oxford',
  'Witney', 'Bicester', 'Banbury', 'Abingdon',
  'Didcot', 'Wallingford', 'Wantage', 'Faringdon',
  'Reading',
  'Caversham', 'Earley', 'Tilehurst', 'Whitley Reading',
  'Woodley', 'Spencers Wood', 'Three Mile Cross',
  'Newbury', 'Thatcham', 'Wokingham', 'Bracknell',
  'Windsor', 'Maidenhead', 'Marlow', 'Henley-on-Thames', 'Burnham Bucks',
  'Slough',
  'Langley Slough', 'Cippenham', 'Chalvey',

  // ── Additional towns & sub-areas ─────────────────────────────────────────
  // More Cumbria
  'Maryport', 'Cockermouth', 'Egremont', 'Millom',
  'Kirkby Stephen', 'Appleby-in-Westmorland',

  // More Yorkshire Dales / Moors
  'Northallerton', 'Thirsk', 'Bedale', 'Leyburn', 'Hawes',
  'Pickering', 'Helmsley', 'Malton', 'Norton-on-Derwent',

  // More Lincolnshire
  'Horncastle', 'Market Rasen', 'Brigg', 'Barton-upon-Humber',
  'Immingham', 'Hessle', 'Goole',

  // More East Midlands
  'Market Harborough', 'Lutterworth',
  'Oakham', 'Uppingham',

  // More South West
  'Seaton Devon', 'Beer Devon', 'Colyton',
  'Bovey Tracey', 'Buckfastleigh', 'Ashburton', 'Tavistock',
  'Holsworthy', 'Bude', 'Camelford', 'Wadebridge',
  'Padstow', 'St Columb Major', 'Perranporth', 'St Agnes Cornwall',
  'Hayle', 'Porthleven', 'Mullion',

  // More South East / Surrey
  'Godalming', 'Haslemere', 'Cranleigh',
  'Lingfield', 'Oxted', 'Caterham', 'Warlingham',
  'Horley', 'Godstone',

  // More Kent
  'Swanley', 'Edenbridge', 'Westerham', 'Biggin Hill',
  'Snodland', 'Aylesford', 'West Malling', 'Larkfield',
  'Sheerness', 'Minster-on-Sea', 'Leysdown-on-Sea',
  'New Romney', 'Lydd', 'Tenterden', 'Cranbrook',

  // More Hampshire / Isle of Wight
  'Romsey', 'Lymington', 'New Milton', 'Ringwood',
  'Fordingbridge', 'Verwood', 'Ferndown',
  'Newport Isle of Wight', 'Ryde', 'Sandown', 'Shanklin',
  'Ventnor', 'Cowes', 'East Cowes',

  // More Sussex
  'Arundel', 'Midhurst', 'Petworth', 'Pulborough',
  'Shoreham-by-Sea', 'Lancing', 'Rottingdean',

  // More Devon / Somerset coast
  'Lynton', 'Lynmouth', 'Porlock', 'Dulverton',
  'Dawlish', 'Teignmouth', 'Shaldon',
  'Salcombe', 'Modbury',

  // More Midlands / rural
  'Leominster', 'Bromyard', 'Kington Herefordshire',
  'Upton upon Severn',
  'Southam', 'Shipston-on-Stour', 'Alcester',
  'Atherstone', 'Polesworth', 'Coleshill',

  // More East Anglia coast
  'Felixstowe', 'Woodbridge', 'Saxmundham', 'Leiston',
  'Aldeburgh', 'Southwold', 'Halesworth',
  'Cromer', 'Sheringham', 'North Walsham', 'Aylsham',
  'Diss',

  // More Hertfordshire
  "Bishop's Stortford", 'Sawbridgeworth',
  'Cheshunt', 'Waltham Abbey',
  'Borehamwood', 'Radlett', 'Potters Bar',
  'Rickmansworth', 'Chorleywood', 'Bricket Wood',
  'Berkhamsted', 'Tring',

  // More Oxfordshire
  'Chipping Norton', 'Burford',
  'Woodstock', 'Kidlington', 'Thame', 'Watlington',

  // More Northamptonshire
  'Brackley', 'Higham Ferrers', 'Irthlingborough',
  'Oundle', 'Thrapston', 'Desborough',

  // More Derbyshire / Peak District
  'Tideswell', 'Hathersage', 'Hope Derbyshire',
  'Ashbourne',

  // More Staffordshire / Cheshire
  'Stone Staffordshire', 'Cheadle Staffordshire',
  'Biddulph', 'Tarporley',

  // More Welsh towns
  'Knighton Powys', 'Presteigne', 'Builth Wells',
  'Hay-on-Wye', 'Talgarth',
  'Blaenavon', 'Ebbw Vale', 'Tredegar', 'Rhymney',
  'Abertillery', 'Brynmawr',

  // More Scottish towns
  'Callander', 'Aberfoyle', 'Dunblane',
  'Dollar', 'Tillicoultry', 'Alva', 'Tullibody',
  'Sauchie', 'Menstrie',
  'Kelty', 'Cowdenbeath', 'Lochgelly', 'Cardenden',
  'Methil', 'Windygates', 'Kennoway',
  'Ballingry', 'Kinross',
  'Comrie', 'Aberfeldy', 'Killin', 'Crianlarich',
  'Tyndrum', 'Dalmally', 'Inveraray', 'Lochgilphead',
  'Tarbert Argyll', 'Campbeltown',
  'Tobermory', 'Bowmore',
  'Girvan', 'Maybole', 'Dalmellington',
  'Kilwinning', 'Beith', 'Dalry Ayrshire',
  'Newmilns', 'Galston', 'Mauchline', 'Cumnock',
  'Sanquhar', 'Moffat', 'Lockerbie', 'Annan',
  'Gretna', 'Langholm',
  'Coldstream', 'Duns', 'Eyemouth',
  'Pathhead',

  // More Northern Irish towns
  'Castlederg', 'Plumbridge', 'Claudy',
  'Maghera', 'Moneymore', 'Stewartstown',
  'Coalisland', 'Moira', 'Hillsborough County Down',
  'Saintfield', 'Crossgar', 'Killyleagh',
  'Ballynahinch', 'Dromore Down', 'Rathfriland',
  'Kilkeel', 'Warrenpoint', 'Rostrevor', 'Hilltown County Down',
  'Irvinestown', 'Lisnaskea', 'Ballyshannon',
  'Belleek', 'Garrison',
];
